### ISSUE TITLE
Git/GitHub icon is not rendered

### ISSUE THREAD

**Issue by vivekragunathan** [haccks/zsh-config#1]
I followed the steps in the README and have got the theme working. In the .zshrc, I uncommented the following hoping to see git/github icons but they don't show up. I am using the suggested Meslo font.

```
POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408 '
```

How do I get the github icon rendered?

**Comment by haccks** [comment]
Did you run `source ~/.zshrc` after the changes? And after that quit the terminal and restart it again to make the changes work.

**Comment by vivekragunathan** [comment]
So, i got it working finally. I restarted iTerm for one. Although, the icon is rendered for all Github and Gitlab repos correctly except for one github repo. Not sure why but I am gonna re-clone and check.

Thanks for the help.

**Comment by vivekragunathan** [comment]
Re-cloning the repo did the trick!
